### ISSUE TITLE
Exception in Bento's Flask usage when invoking Sagemaker endpoint

### ISSUE THREAD

**Issue by eob** [bentoml/aws-sagemaker-deploy#11]
Hi there!

I just bundled and deployed a Pytorch image using the `deploy.py` file. Everything seems to deploy fine, but when I invoke the endpoint it crashed because BentoML is using a Flask call that appears not to exist. 

I'm not sure if I've configured something wrong or if there's a version mismatch somewhere in the Bento + Docker stack.

Here is how I am invoking my endpoint:

```
aws sagemaker-runtime invoke-endpoint \
  --endpoint-name my-endpoint-name \
  --body '{"data":["foo"]}' \
  --cli-binary-format raw-in-base64-out \
  --content-type "application/json" \
  >(cat) 1>/dev/null | echo
```

In the logs, here is what that invocation looks like:

```
10.32.0.2 - - [25/Aug/2021:18:03:12 +0000] "POST /invocations HTTP/1.1" 500 290 "-" "AHC/2.0"
```

And then here is the exception that follows:

```
[2021-08-25 18:03:12,772] ERROR in app: Exception on /invocations [POST]

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/conda/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/conda/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/bento/wsgi.py", line 25, in view_function
    response = api.handle_request(req)
  File "/opt/conda/lib/python3.8/site-packages/bentoml/service/inference_api.py", line 295, in handle_request
    req = HTTPRequest.from_flask_request(request)
  File "/opt/conda/lib/python3.8/site-packages/bentoml/types.py", line 241, in from_flask_request
    tuple((k, v) for k, v in request.headers.items()), request.get_data(),

AttributeError: 'HTTPRequest' object has no attribute 'get_data'
```

**Comment by eob** [comment]
@jjmachan Thanks for the response.

* Upgrading to .13.1 worked for me using the scripts in this repository.

If I deployed the Docker image to ECR separately and created my own endpoint via Terraform, for some reason I was still getting it. I tracked it down to having an old version of Flask inside the docker container, and solved the problem by adding:

```
RUN pip install flask>=2.0.1
```

...to the inlined Dockerfile in `generate_deployable.py`

I think my use case is a bit out of scope for this codebase, but I wanted to report my fix here just in case it's helpful to someone else.
